name: debug

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Show IP info
        run: |
          curl ifconfig.io
          echo "runner:runner" | sudo chpasswd
          sudo systemctl start ssh

      - name: Download and setup Xray
        run: |
          # 下载 Xray 二进制
          curl -L https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip -o /tmp/Xray.zip
          unzip /tmp/Xray.zip -d /tmp/xray-tmp
          sudo cp /tmp/xray-tmp/xray /usr/local/bin/xray
          sudo chmod +x /usr/local/bin/xray

          # 下载 Xray 配置文件
          sudo mkdir -p /etc/xray
          curl -L https://github.com/pornnewbee/socks5-for-serv00/raw/refs/heads/main/Configs/V2Ray/config.json -o config.json
          sudo mv config.json /etc/xray/

          # 下载并安装 systemd 服务文件
          curl -L https://github.com/pornnewbee/socks5-for-serv00/raw/refs/heads/main/Configs/V2Ray/xray.service -o xray.service
          sudo mv xray.service /etc/systemd/system/

      - name: Start Xray service
        run: |
          sudo systemctl daemon-reload
          sudo systemctl enable xray
          sudo systemctl start xray
          sudo systemctl status xray --no-pager

      - name: Install latest cloudflared
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared
          sudo mv cloudflared /usr/local/bin/
          cloudflared --version
          sudo cloudflared service install eyJhIjoiOGQyMDg4NjE0Nzg1N2EwY2RjYzhkYjc3OGU4YjZlZjciLCJ0IjoiOTgwZjE4ZDYtOTJjYS00MGU1LTkzYTItODIxZWUxMjVhYmFjIiwicyI6IlpURmxOemxrWXprdFptRTROQzAwWTJNd0xXSmxNR0V0WldZeFlqa3daRGt3T1RneiJ9
          sudo rm -rf ~/tmp

      - name: debug
        run: sleep 99999
